### ISSUE TITLE
What about Guava Immutable Collections?

### ISSUE THREAD

**Issue by idcmp** [pure4j/pure4j#5]
Are constructors making defensive immutable copies of collections good enough?

  https://github.com/google/guava/wiki/ImmutableCollectionsExplained

**Comment by robmoffat** [comment]
Hi idcmp,

Good enough for what?

If you mean, good enough to ensure that using them is functionally pure, then the answer is no:   Although the collection itself is immutable, the values it contains won't (necessarily) be immutable.  Obviously, a collection of `String`s would be, but you could have a collection of `Object`s...

Also, because they're immutable, they're not going to be useful if you want to make changes to the data structures.  This is why pure4J uses persistent collections (from Clojure). More details are [here](https://github.com/pure4j/pure4j/blob/master/docs/tutorial_collections.md).

There are also wrappers round the java collections so that they can be used in a `@MutableUnshared` way.  This is useful if you are worried about performance -- remember not to optimise early, though ;)  

Some details on those [here](https://github.com/pure4j/pure4j/blob/master/docs/tutorial_mutable_unshared.md)

**Comment by robmoffat** [comment]
Does that help?

**Comment by idcmp** [comment]
I'm in a fairly large code base where we have many @Immutable classes (we copy collections and mutable classes), I was hoping pure4j could catch people making honest mistakes. Many of my use cases are such that I don't actually want to change the data in the immutable collections once they're made. I'm starting to drink the functional koolaid, and enjoy what it's saying, but haven't fully grasped everything, so I'm going to need to think on this a bit.

**Comment by robmoffat** [comment]
Are you using net.jcip.annotations.Immutable?

**Comment by idcmp** [comment]
javax.annotation.concurrent.Immutable, but same generally philosophy.

**Comment by robmoffat** [comment]
Is there an annotation processor for that that you are using?

With regard to the guava collections (and this is something I was thinking of doing anyway, although for some reason I didn't add a ticket already), I think it would be good if you could tell the checker that these could be considered pure, in much the same way as pure4j already knows which methods are pure on many JVM classes.

So, you might add an annotation in your code like this:

```java
@RegisterImmutableValues({ImmutableSortedSet.class, ImmutableTable.class})
```

In terms of immutability, the guava collections are completely immutable if you (& your team) only put other immutable objects inside them. But, you would have to ensure this yourself.  cf. Using the pure4j collections where you would get this guarantee.

In terms of purity, there will obviously be no state changing, and they are unlikely to have IO side-effects so this would probably be pretty safe for your purposes.

thoughts?

**Comment by idcmp** [comment]
We enforce immutability through code reviews, culture and lots of existing examples to follow. People still trip up sometimes (every now and then accidentally including mutable objects (Date, etc) in immutable collections, etc). We have no processor yet (this is why pure4j is interesting to me). 

I forsee us running pure4j as a Maven plugin during "mvn install" on our desktops (assuming it's not unusually unperformant). I think it would be more handy to be able to include the registered immutable values in the plugin configuration (instead of code), but yes being able to add the guava immutable collections would be a great first step for us to enforce the immutability.

Again, I'm new to much of this, so if I'm not making sense it's likely showing my lack of full understanding. :)

**Comment by fzoozai** [comment]
@robmoffat 
With regard to your first post when you said the following: "Obviously, a collection of Strings would be, but you could have a collection of Objects..." I've often read about that issue with objects in such a collection but still couldn't find a concrete example for a collection of Objects where I should get in trouble with. Could you illustrate it on a simple code snippet example. Would be great for understanding it properly. 
Cheers!
