### ISSUE TITLE
Annotation for specifying that an implementation function must be pure

### ISSUE THREAD

**Issue by nedtwigg** [pure4j/pure4j#9]
I have two questions which I couldn't find in the docs:

Let's say I have a class like this:

```java
abstract class Strict<State> {
    State state;

    @Pure
    protected abstract String functionThatMustBePure(State state, String input);

    public String apply(String input) {
        return functionThatMustBePure(state, input);
    }
}
```

Can I use the `@Pure` annotation in this way, to enforce that subclasses implement the function in a pure way?

Along the same lines, is it possible to annotate a `@FunctionalInterface` argument of a function to be pure?

```java
public static Supplier<R> memoizeResult(T input, @Pure Function<T, R> result) { ... }
```

**Comment by robmoffat** [comment]
Hi Ned,

Your first question:  Yes, that's exactly how it works.  Subclasses must respect the annotations of the interface / superclass.

Second question:    It's a while since I looked at it, but I don't think you can say only a single argument should be pure - when you declare a pure method, all the arguments being passed in must be pure (checked at compile time or runtime).

cheers,

Rob
